[2025-08-17T16:54:18.356+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-17T16:54:18.389+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: excel_to_mysql_daily_7am.load_to_mysql manual__2025-08-17T16:41:40.170117+00:00 [queued]>
[2025-08-17T16:54:18.397+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: excel_to_mysql_daily_7am.load_to_mysql manual__2025-08-17T16:41:40.170117+00:00 [queued]>
[2025-08-17T16:54:18.397+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-17T16:54:18.409+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_to_mysql> on 2025-08-17 16:41:40.170117+00:00
[2025-08-17T16:54:18.417+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'excel_to_mysql_daily_7am', 'load_to_mysql', 'manual__2025-08-17T16:41:40.170117+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/excel_to_mysql_dag.py', '--cfg-path', '/tmp/tmpzaxgwyy1']
[2025-08-17T16:54:18.419+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask load_to_mysql
[2025-08-17T16:54:18.421+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=465) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-17T16:54:18.422+0000] {standard_task_runner.py:63} INFO - Started process 467 to run task
[2025-08-17T16:54:18.488+0000] {task_command.py:426} INFO - Running <TaskInstance: excel_to_mysql_daily_7am.load_to_mysql manual__2025-08-17T16:41:40.170117+00:00 [running]> on host 9e46b3905fa0
[2025-08-17T16:54:18.611+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='excel_to_mysql_daily_7am' AIRFLOW_CTX_TASK_ID='load_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2025-08-17T16:41:40.170117+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-17T16:41:40.170117+00:00'
[2025-08-17T16:54:18.613+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-17T16:54:18.629+0000] {base.py:84} INFO - Using connection ID 'mysql_target' for task execution.
[2025-08-17T16:54:18.811+0000] {python.py:237} INFO - Done. Returned value was: 800
[2025-08-17T16:54:18.811+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-17T16:54:18.845+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=excel_to_mysql_daily_7am, task_id=load_to_mysql, run_id=manual__2025-08-17T16:41:40.170117+00:00, execution_date=20250817T164140, start_date=20250817T165418, end_date=20250817T165418
[2025-08-17T16:54:18.877+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-17T16:54:18.904+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-17T16:54:18.906+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
